apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080        # External port to expose
    targetPort: 8080  # Container's port
  selector:
    app: go-app       # Matches labels in go-app deployment
